/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file Common power.h include for Nordic SoCs.
 */

#ifndef _ZEPHYR_SOC_ARM_NORDIC_NRF_POWER_H_
#define _ZEPHYR_SOC_ARM_NORDIC_NRF_POWER_H_

#if defined(NRF_APPLICATION)
#define RAMBLOCK_CONTROL_BIT_ICACHE MEMCONF_POWER_CONTROL_MEM1_Pos
#define RAMBLOCK_CONTROL_BIT_DCACHE MEMCONF_POWER_CONTROL_MEM2_Pos
#define RAMBLOCK_POWER_ID	    0
#define RAMBLOCK_CONTROL_OFF	    0
#define RAMBLOCK_RET_MASK	    (MEMCONF_POWER_RET_MEM0_Msk)
#define RAMBLOCK_RET2_MASK	    (MEMCONF_POWER_RET2_MEM0_Msk)
#define RAMBLOCK_RET_BIT_ICACHE	    MEMCONF_POWER_RET_MEM1_Pos
#define RAMBLOCK_RET_BIT_DCACHE	    MEMCONF_POWER_RET_MEM2_Pos
#define RAMBLOCK_RET2_BIT_ICACHE    MEMCONF_POWER_RET2_MEM1_Pos
#define RAMBLOCK_RET2_BIT_DCACHE    MEMCONF_POWER_RET2_MEM2_Pos
#elif defined(NRF_RADIOCORE)
#define RAMBLOCK_CONTROL_BIT_ICACHE MEMCONF_POWER_CONTROL_MEM6_Pos
#define RAMBLOCK_CONTROL_BIT_DCACHE MEMCONF_POWER_CONTROL_MEM7_Pos
#define RAMBLOCK_POWER_ID	    0
#define RAMBLOCK_CONTROL_OFF	    0
#define RAMBLOCK_RET_MASK	    (MEMCONF_POWER_RET_MEM0_Msk | MEMCONF_POWER_RET_MEM1_Msk | \
				     MEMCONF_POWER_RET_MEM2_Msk | MEMCONF_POWER_RET_MEM3_Msk | \
				     MEMCONF_POWER_RET_MEM4_Msk | MEMCONF_POWER_RET_MEM5_Msk | \
				     MEMCONF_POWER_RET_MEM8_Msk)
#define RAMBLOCK_RET2_MASK	    (MEMCONF_POWER_RET2_MEM0_Msk | MEMCONF_POWER_RET2_MEM1_Msk | \
				     MEMCONF_POWER_RET2_MEM2_Msk | MEMCONF_POWER_RET2_MEM3_Msk | \
				     MEMCONF_POWER_RET2_MEM4_Msk | MEMCONF_POWER_RET2_MEM5_Msk | \
				     MEMCONF_POWER_RET2_MEM8_Msk)
#define RAMBLOCK_RET_BIT_ICACHE	    MEMCONF_POWER_RET_MEM6_Pos
#define RAMBLOCK_RET_BIT_DCACHE	    MEMCONF_POWER_RET_MEM7_Pos
#define RAMBLOCK_RET2_BIT_ICACHE    MEMCONF_POWER_RET2_MEM6_Pos
#define RAMBLOCK_RET2_BIT_DCACHE    MEMCONF_POWER_RET2_MEM7_Pos
#else
#error "Unsupported domain."
#endif

/**
 * @brief Perform a power off.
 *
 * This function performs a power off of the core.
 */
void nrf_poweroff(void);

#endif /* _ZEPHYR_SOC_ARM_NORDIC_NRF_POWER_H_ */
